Implemented Order Actions: Print, Cancel and CreateInvoice
zenta-ab/fortnox.NET pull request #26
Opened 2020-11-13 15:09 UTC by kwestground

### Description
Please explain the changes you made here.

### Checklist
- [Y] Code compiles correctly
- [Y] Created tests which fail without the change (if possible)
- [Y] Extended the README / documentation, if necessary

2020-11-13 22:33 UTC, brokenprogrammer requested changes
Thank you once again for your contributions @kwestground! It is very much appreciated 🙏
I just had a few comments on the pull request, will merge once addressed!

2020-11-13 22:33 UTC, brokenprogrammer commented on Fortnox.NET/Services/OrderService.cs
> +        public static async Task<Order> PrintAsync(FortnoxApiRequest request, int orderNumber)
The name of this method might be confused with the actual print action for orders. Perhaps a name like `ExternalPrintAsync` is more fitting?

2020-11-13 22:33 UTC, brokenprogrammer commented on Fortnox.NET/Services/OrderService.cs
> +        /// <summary>
Its awesome that you've started adding documentation to the library! This is something that we've been wanting to get started on but didn't get to yet. 💯 👍

2020-11-13 22:33 UTC, brokenprogrammer commented on Fortnox.NET/Services/OrderService.cs
> +        /// <returns></returns>
Perhaps fill in the returns as well.

2020-11-13 22:33 UTC, brokenprogrammer commented on Fortnox.NET/Services/OrderService.cs
> +        public static async Task<Order> CancelAsync(FortnoxApiRequest request, int orderNumber)
Would you like to add documentation for theese methods as well?

2020-11-13 22:33 UTC, brokenprogrammer commented on Fortnox.NET.Tests/Fortnox.NET.Tests/OrderTests.cs
> +            Assert.AreEqual("1", createInvoiceResponse.CustomerNumber);
The CreateInvoice action sets an `InvoiceReference` for the order in, a more interesting test would be to check if it actually got a new reference to an invoice.

2020-11-27 07:08 UTC, brokenprogrammer approved these changes
I've reviewed the pull request now and tested it and it looks great to me.
Once again thanks for your contributions @kwestground 🙏

2020-11-27 07:08 UTC, merged

2020-11-27 08:29 UTC, GGAlanSmithee commented
Thanks for you contribution @kwestground 🥂